name: bintray-publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: client/java
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: client/java
    - name: Publish to Bintray
      run: ./gradlew bintrayUpload
      working-directory: client/java